name: 刷

on:
  workflow_dispatch:
    inputs:
      user:
        description: '17753852041'
        required: true
        default: ''
      pwd:
        description: 'nimei14753'
        required: true
        default: ''
      step:
        description: '2022'
        required: false
        default: '0'

  

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        pip install requests
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        
        python3 main.py <<EOF
        ${user}
        ${pwd}
        ${step}
        EOF
